version: '3.8'
services:
  database:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    container_name: micro-container
    restart: always
    environment:
      - MYSQL_DATABASE=micro-container
      - MYSQL_USER=micro-container
      - MYSQL_PASSWORD=micro-container
      - MYSQL_ROOT_PASSWORD=micro-container
      - TZ=UTC
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass MDNcVb924a
    ports:
      - '6379:6379'